Search for errors/warnings in error log and stop if found

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,6 +49,14 @@ jobs:
         run: sudo apachectl configtest
       - name: start apache with module
         run: sudo systemctl restart apache2.service
+      - name: Search for errors/warnings in error log
+        run: |
+          errors="$(grep -E ":(?error|warn)[]]" /var/log/apache2/error.log)"
+          if [ -n "${errors}" ]; then
+            echo "Found errors/warnings in error.log"
+            echo "${errors}"
+            exit 1
+          fi
       - name: Show httpd error log
         if: always()
         run: sudo cat /var/log/apache2/error.log
